import { IField } from 'src/app/core/dtos/IFields';

export const accountFields: IField[] = [
  {
    key: 'username',
    label: 'Username',
    placeholder: '',
    type: 'text',
    isRequired: true,
    regexPattern: '',
  },
  {
    key: 'password',
    label: 'Password',
    placeholder: '',
    type: 'password',
    isRequired: true,
    regexPattern: '',
  },
  {
    key: 'first_name',
    label: 'First Name',
    placeholder: '',
    type: 'text',
    isRequired: true,
    regexPattern: '',
  },
  {
    key: 'last_name',
    label: 'Last Name',
    placeholder: '',
    type: 'text',
    isRequired: true,
    regexPattern: '',
  },
  {
    key: 'email',
    label: 'Email',
    placeholder: '',
    type: 'text',
    isRequired: true,
    regexPattern: '',
  },
  {
    key: 'id_card',
    label: 'ID Card',
    placeholder: '',
    type: 'text',
    isRequired: true,
    regexPattern: '^[0-9]*$',
  },
  {
    key: 'role',
    label: 'Role',
    placeholder: '',
    type: 'select',
    isRequired: true,
    regexPattern: '',
  },
  {
    key: 'phone_number',
    label: 'Phone Number',
    placeholder: '',
    type: 'text',
    isRequired: true,
    regexPattern: '',
  },
];
